[package]
name = "simple_audio"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
cpal = "0.14.1"
flutter_rust_bridge = "1"
reqwest = { version = "0.11.12", features = ["blocking"] }
symphonia = { version = "0.5.1", features = ["aac", "alac", "isomp4", "mp3"] }
rb = "0.4.1"
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }