[package]
name = "simple_audio"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "1"
symphonia = { version = "0.5.1", features = ["aac", "alac", "mp3", "isomp4"] }
reqwest = { version = "0.11.12", features = ["blocking"] }

[dependencies.rodio]
version = "0.16.0"
features = ["symphonia-all", "symphonia"]
default-features = false
