[package]
name = "simple_audio"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
cpal = "0.14.1"
flutter_rust_bridge = "1"
reqwest = { version = "0.11.12", features = ["blocking"] }
symphonia = { version = "0.5.1", features = ["aac", "alac", "isomp4", "mp3"] }
rb = "0.4.1"
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
openssl-sys = { version = "0.9.77", features = ["vendored"] }

[target.'cfg(all(unix, not(target_os = "macos"), not(target_os = "android"), not(target_os = "ios")))'.dependencies]
dbus = "0.9.6"
dbus-crossroads = "0.5.1"

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { git = "https://github.com/rust-windowing/android-ndk-rs" }
oboe = { version = "0.4.6", features = [ "java-interface", "shared-stdcxx" ] }

# target.'cfg(target_os = "windows")'.
[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.43.0"
features = [
	"Foundation",
	"Media",
	"Win32_Foundation",
	"Win32_System_WinRT",
	"Storage_Streams",
]