name: CI

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: ./.github/actions/setup_build

      - name: Install Rust -sys dependencies
        run: |
          sudo apt install libasound2-dev
          sudo apt install libdbus-1-dev pkg-config

      - name: Build Linux Library
        run: python ./plugin_tool.py -b linux

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: ./.github/actions/setup_build

      - name: Build Android Libraries
        run: python ./plugin_tool.py -b android

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: ./.github/actions/setup_build

      - name: Build Windows Library
        run: python3 .\plugin_tool.py -b windows

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: ./.github/actions/setup_build

      - name: Build macOS Libraries
        run: python ./plugin_tool.py -b macos

  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: ./.github/actions/setup_build

      - name: Build iOS Libraries
        run: python ./plugin_tool.py -b ios
